#!/usr/bin/env python3
"""
Build "AIS Wi-Fi Auto-Login.app", a regular macOS app for the menu bar tool.

Usage:
    python3 make_app.py            # build and install into /Applications (or ~/Applications)
    python3 make_app.py --open     # ... and start it
    python3 make_app.py --dest DIR # install somewhere else

The bundle contains a copy of the source code and a tiny compiled launcher
that runs it in-process with THIS Python interpreter and its installed
packages (so install the requirements first). Because it is a real app, it
shows up in Launchpad/Spotlight, can be added to Login Items ("Open at Login"
in the menu), and macOS permissions such as Full Disk Access belong to the
app itself instead of Terminal.

Rebuild after updating the code (quit the running app first). The C compiler
comes with the Xcode Command Line Tools: `xcode-select --install`.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import site
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from aiswifi import __app_name__, __bundle_id__, __version__  # noqa: E402

EXECUTABLE = "AISWiFiAutoLogin"

LAUNCHER_C = r"""
/* Generated by make_app.py: runs Contents/Resources/launch.py in-process. */
#include <Python.h>
#include <limits.h>
#include <mach-o/dyld.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[]) {
    char exe[PATH_MAX], dir[PATH_MAX], script[PATH_MAX];
    uint32_t size = sizeof(exe);
    if (_NSGetExecutablePath(exe, &size) != 0 || realpath(exe, dir) == NULL) {
        fprintf(stderr, "Cannot determine the executable path\n");
        return 1;
    }
    *strrchr(dir, '/') = '\0';  /* .../Contents/MacOS */
    snprintf(script, sizeof(script), "%s/../Resources/launch.py", dir);
    setenv("PYTHONHOME", PYTHON_HOME, 1);
    /* Never write .pyc files into the (signed) bundle. */
    setenv("PYTHONDONTWRITEBYTECODE", "1", 1);

    char **args = calloc((size_t)argc + 2, sizeof(char *));
    if (args == NULL) return 1;
    args[0] = argv[0];
    args[1] = script;
    for (int i = 1; i < argc; i++) args[i + 1] = argv[i];
    return Py_BytesMain(argc + 1, args);
}
"""

LAUNCH_PY = """\
# Generated by make_app.py — rebuild the app instead of editing this file.
import os
import site
import sys

# Packages installed for the interpreter that built the app (venv/user site too).
for d in {site_dirs!r}:
    if os.path.isdir(d):
        site.addsitedir(d)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "app"))

import run  # noqa: E402

sys.exit(run.main(sys.argv[1:]))
"""


def _site_dirs() -> List[str]:
    dirs = list(site.getsitepackages())
    user = site.getusersitepackages()
    if isinstance(user, str):
        dirs.append(user)
    return dirs


def _link_flags() -> List[str]:
    """Linker flags for embedding this interpreter (shared or framework builds)."""
    framework = sysconfig.get_config_var("PYTHONFRAMEWORK")
    if framework:
        prefix = sysconfig.get_config_var("PYTHONFRAMEWORKPREFIX")
        return [f"-F{prefix}", "-framework", framework, f"-Wl,-rpath,{prefix}"]
    if sysconfig.get_config_var("Py_ENABLE_SHARED"):
        libdir = sysconfig.get_config_var("LIBDIR")
        return [f"-L{libdir}", f"-lpython{sysconfig.get_config_var('LDVERSION')}",
                f"-Wl,-rpath,{libdir}"]
    sys.exit("This Python has a static libpython and cannot be embedded in an app.\n"
             "Use a python.org or Homebrew Python, or with pyenv reinstall it with:\n"
             "  env PYTHON_CONFIGURE_OPTS=--enable-shared pyenv install <version>")


def _compile_launcher(output: Path, workdir: Path) -> None:
    source = workdir / "launcher.c"
    source.write_text(LAUNCHER_C, encoding="utf-8")
    cmd = ["clang", "-O2", f"-I{sysconfig.get_config_var('INCLUDEPY')}",
           f'-DPYTHON_HOME="{sys.base_prefix}"', str(source), "-o", str(output),
           *_link_flags()]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except FileNotFoundError:
        sys.exit("clang not found. Install the Xcode Command Line Tools: xcode-select --install")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"Compiling the launcher failed:\n{exc.stderr}")


def _make_icon(icns_path: Path, workdir: Path) -> bool:
    """Render the 🛜 emoji on a rounded square into an .icns file (best effort)."""
    try:
        from AppKit import (  # type: ignore
            NSAttributedString, NSBezierPath, NSBitmapImageFileTypePNG, NSBitmapImageRep,
            NSColor, NSDeviceRGBColorSpace, NSFont, NSFontAttributeName, NSGradient,
            NSGraphicsContext, NSMakePoint, NSMakeRect,
        )
        iconset = workdir / "AppIcon.iconset"
        iconset.mkdir()
        for points in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                px = points * scale
                rep = NSBitmapImageRep.alloc().initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel_(  # noqa: E501
                    None, px, px, 8, 4, True, False, NSDeviceRGBColorSpace, 0, 0)
                NSGraphicsContext.saveGraphicsState()
                NSGraphicsContext.setCurrentContext_(
                    NSGraphicsContext.graphicsContextWithBitmapImageRep_(rep))
                inset = px * 0.1
                side = px - 2 * inset
                shape = NSBezierPath.bezierPathWithRoundedRect_xRadius_yRadius_(
                    NSMakeRect(inset, inset, side, side), side * 0.225, side * 0.225)
                NSGradient.alloc().initWithStartingColor_endingColor_(
                    NSColor.colorWithSRGBRed_green_blue_alpha_(1.0, 1.0, 1.0, 1.0),
                    NSColor.colorWithSRGBRed_green_blue_alpha_(0.86, 0.89, 0.94, 1.0),
                ).drawInBezierPath_angle_(shape, -90)
                emoji = NSAttributedString.alloc().initWithString_attributes_(
                    "🛜", {NSFontAttributeName: NSFont.fontWithName_size_("Apple Color Emoji", side * 0.66)})
                size = emoji.size()
                emoji.drawAtPoint_(NSMakePoint((px - size.width) / 2, (px - size.height) / 2))
                NSGraphicsContext.restoreGraphicsState()
                name = f"icon_{points}x{points}{'@2x' if scale == 2 else ''}.png"
                png = rep.representationUsingType_properties_(NSBitmapImageFileTypePNG, {})
                png.writeToFile_atomically_(str(iconset / name), True)
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns_path)],
                       check=True, capture_output=True)
        return True
    except Exception as exc:
        print(f"Warning: could not create the app icon ({exc}); using the default icon.")
        return False


def build(dest_dir: Path) -> Path:
    """Build the app bundle and install it into `dest_dir`. Returns the app path."""
    app_name = f"{__app_name__}.app"
    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        app = workdir / app_name
        macos = app / "Contents" / "MacOS"
        resources = app / "Contents" / "Resources"
        macos.mkdir(parents=True)
        resources.mkdir()

        # 1) Source code snapshot
        shutil.copytree(ROOT / "aiswifi", resources / "app" / "aiswifi",
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        shutil.copy2(ROOT / "run.py", resources / "app" / "run.py")
        (resources / "launch.py").write_text(LAUNCH_PY.format(site_dirs=_site_dirs()),
                                             encoding="utf-8")

        # 2) Launcher and icon
        _compile_launcher(macos / EXECUTABLE, workdir)
        has_icon = _make_icon(resources / "AppIcon.icns", workdir)

        # 3) Info.plist
        info = {
            "CFBundleDevelopmentRegion": "en",
            "CFBundleDisplayName": __app_name__,
            "CFBundleExecutable": EXECUTABLE,
            "CFBundleIdentifier": __bundle_id__,
            "CFBundleInfoDictionaryVersion": "6.0",
            "CFBundleName": __app_name__,
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": __version__,
            "CFBundleVersion": __version__,
            "LSApplicationCategoryType": "public.app-category.utilities",
            "LSMinimumSystemVersion": "11.0",
            "LSUIElement": True,  # menu bar app: no Dock icon
            "NSHighResolutionCapable": True,
        }
        if has_icon:
            info["CFBundleIconFile"] = "AppIcon"
        with open(app / "Contents" / "Info.plist", "wb") as fh:
            plistlib.dump(info, fh)

        # 4) Ad-hoc signature (a stable identity for macOS permissions and Login Items)
        subprocess.run(["codesign", "--force", "--deep", "--sign", "-", str(app)],
                       check=True, capture_output=True)

        # 5) Install (ditto keeps the signature intact)
        dest_dir.mkdir(parents=True, exist_ok=True)
        target = dest_dir / app_name
        if target.exists():
            shutil.rmtree(target)
        subprocess.run(["ditto", str(app), str(target)], check=True)
    return target


def _default_dest() -> Path:
    system_apps = Path("/Applications")
    if os.access(system_apps, os.W_OK):
        return system_apps
    return Path.home() / "Applications"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=f"Build {__app_name__}.app")
    parser.add_argument("--dest", type=Path, default=None,
                        help="install folder (default: /Applications, or ~/Applications)")
    parser.add_argument("--open", action="store_true", help="start the app after building")
    args = parser.parse_args(argv)

    if sys.platform != "darwin":
        sys.exit("The app can only be built on macOS.")
    target = build(args.dest or _default_dest())
    print(f"Installed: {target}")
    print("Start it from Applications/Launchpad/Spotlight. To start it automatically, "
          "enable 'Open at Login' in its menu.")
    if args.open:
        subprocess.run(["open", str(target)], check=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
